[package]
name = "logs-publisher"
version = "0.1.0"
edition = "2018"

[dependencies]
# Mqtt
paho-mqtt = "0.9"

# Watching file
logwatcher = "0.1.1"

#log
log = "0.4.14"
simple_logger = "1.11.0"

clap = "2.33.3"

